// Mock data for static deployment without backend

export const mockBusinesses = [
  { id: 1, name: "Tamarind Lodges", category: "Lodges", subCategory: "Safari Lodge", country: "Zimbabwe", city: "Kariba", address: "Lake Kariba Shoreline", phone: "+263772123456", whatsapp: "+263772123456", email: "info@tamarindlodges.co.zw", facebookUrl: "https://facebook.com/tamarindlodges", rating: "4.2", reviewCount: 34, hasWebsite: false, hasFacebook: true, hasWhatsapp: true, digitalScore: 22, opportunityLevel: "very_high" as const, source: "google_maps" },
  { id: 2, name: "Victoria Falls Hotel", category: "Hotels", subCategory: "Luxury Hotel", country: "Zimbabwe", city: "Victoria Falls", address: "1 Mallet Drive", phone: "+263213284574", whatsapp: "+263213284575", email: "reservations@vfallshotel.com", website: "https://vfallshotel.com", facebookUrl: "https://facebook.com/vfallshotel", instagramUrl: "https://instagram.com/vfallshotel", rating: "4.6", reviewCount: 892, hasWebsite: true, hasFacebook: true, hasWhatsapp: true, digitalScore: 68, opportunityLevel: "medium" as const, source: "google_maps" },
  { id: 3, name: "Kariba Houseboats Adventures", category: "Houseboats", subCategory: "Houseboat Rental", country: "Zimbabwe", city: "Kariba", address: "Kariba Marina", phone: "+263772987654", whatsapp: "+263772987654", email: "bookings@karibahouseboats.com", facebookUrl: "https://facebook.com/karibahouseboats", rating: "4.0", reviewCount: 18, hasWebsite: false, hasFacebook: true, hasWhatsapp: true, digitalScore: 15, opportunityLevel: "very_high" as const, source: "google_maps" },
  { id: 4, name: "The Boma Restaurant", category: "Restaurants", subCategory: "African Cuisine", country: "Zimbabwe", city: "Victoria Falls", address: "Stanley Livingstone Estate", phone: "+263213284500", whatsapp: "+263772345678", email: "dining@theboma.co.zw", website: "https://theboma.co.zw", facebookUrl: "https://facebook.com/thebomavictoriafalls", instagramUrl: "https://instagram.com/thebomavf", rating: "4.7", reviewCount: 567, hasWebsite: true, hasFacebook: true, hasWhatsapp: true, digitalScore: 72, opportunityLevel: "low" as const, source: "google_maps" },
  { id: 5, name: "Gorges Lodge", category: "Lodges", subCategory: "Boutique Lodge", country: "Zimbabwe", city: "Victoria Falls", address: "Gorges Road, Chinotimba", phone: "+263772456789", whatsapp: "+263772456789", email: "stay@gorgeslodge.co.zw", facebookUrl: "https://facebook.com/gorgeslodge", rating: "4.4", reviewCount: 42, hasWebsite: false, hasFacebook: true, hasWhatsapp: false, digitalScore: 28, opportunityLevel: "high" as const, source: "google_maps" },
  { id: 6, name: "Sundowner Cruise Co", category: "Tours", subCategory: "Boat Cruise", country: "Zimbabwe", city: "Kariba", address: "Kariba Harbour", phone: "+263772567890", whatsapp: "+263772567890", email: "cruise@sundownerkariba.com", rating: "3.8", reviewCount: 12, hasWebsite: false, hasFacebook: false, hasWhatsapp: true, digitalScore: 8, opportunityLevel: "very_high" as const, source: "google_maps" },
  { id: 7, name: "Amanzi Spa & Salon", category: "Salons", subCategory: "Beauty Salon", country: "Zimbabwe", city: "Harare", address: "Samora Machel Avenue", phone: "+263242123456", whatsapp: "+263772678901", email: "bookings@amanzispa.co.zw", facebookUrl: "https://facebook.com/amanzispa", instagramUrl: "https://instagram.com/amanzispa", rating: "4.1", reviewCount: 23, hasWebsite: false, hasFacebook: true, hasWhatsapp: true, digitalScore: 18, opportunityLevel: "high" as const, source: "google_maps" },
  { id: 8, name: "Mukuvisi Woodlands", category: "Tours", subCategory: "Nature Reserve", country: "Zimbabwe", city: "Harare", address: "Mukuvisi Road", phone: "+263242789012", whatsapp: "+263772789012", email: "info@mukuvisi.org", website: "https://mukuvisi.org", facebookUrl: "https://facebook.com/mukuvisi", rating: "4.3", reviewCount: 156, hasWebsite: true, hasFacebook: true, hasWhatsapp: false, digitalScore: 45, opportunityLevel: "medium" as const, source: "google_maps" },
  { id: 9, name: "Cape Grace Hotel", category: "Hotels", subCategory: "Boutique Hotel", country: "South Africa", city: "Cape Town", address: "West Quay Road, V&A Waterfront", phone: "+27214101800", whatsapp: "+27821234567", email: "reservations@capegrace.com", website: "https://capegrace.com", facebookUrl: "https://facebook.com/capegrace", instagramUrl: "https://instagram.com/capegrace", rating: "4.8", reviewCount: 1234, hasWebsite: true, hasFacebook: true, hasWhatsapp: true, digitalScore: 82, opportunityLevel: "low" as const, source: "google_maps" },
  { id: 10, name: "Table Mountain Safari", category: "Safari", subCategory: "Wildlife Safari", country: "South Africa", city: "Cape Town", address: "Long Street", phone: "+27215551234", whatsapp: "+27829876543", email: "tours@tablemountainsafari.co.za", facebookUrl: "https://facebook.com/tmsafari", rating: "3.9", reviewCount: 67, hasWebsite: false, hasFacebook: true, hasWhatsapp: true, digitalScore: 25, opportunityLevel: "high" as const, source: "google_maps" },
  { id: 11, name: "Sossusvlei Desert Lodge", category: "Lodges", subCategory: "Desert Lodge", country: "Namibia", city: "Sesriem", address: "Sossusvlei Road", phone: "+26463293000", whatsapp: "+264811234567", email: "reservations@sossusvleilodge.com", website: "https://sossusvleilodge.com", facebookUrl: "https://facebook.com/sossusvleilodge", instagramUrl: "https://instagram.com/sossusvleilodge", rating: "4.9", reviewCount: 445, hasWebsite: true, hasFacebook: true, hasWhatsapp: true, digitalScore: 76, opportunityLevel: "medium" as const, source: "google_maps" },
  { id: 12, name: "Chobe River Lodge", category: "Lodges", subCategory: "River Lodge", country: "Botswana", city: "Kasane", address: "Chobe River Front", phone: "+2676250336", whatsapp: "+26774123456", email: "bookings@chobelodge.co.bw", facebookUrl: "https://facebook.com/chobelodge", rating: "4.3", reviewCount: 89, hasWebsite: false, hasFacebook: true, hasWhatsapp: true, digitalScore: 31, opportunityLevel: "high" as const, source: "google_maps" },
];

export const mockAnalyses = [
  { id: 1, businessId: 1, overallScore: 22, scoreCategory: "poor" as const, websiteScore: 0, mobileScore: 0, seoScore: 10, brandingScore: 30, socialScore: 25, facebookScore: 28, adScore: 15, visibilityScore: 20, whatsappScore: 45, mapsScore: 38, detectedIssues: JSON.stringify(["Missing website", "Weak Facebook presence", "No booking system", "Poor Google Maps optimization"]), aiSummary: "Tamarind Lodges has significant digital gaps. No website, minimal social activity, and no booking automation. High opportunity for digital services.", generatedPitch: "Hi Tamarind Lodges team! I noticed your beautiful lakeside property has amazing potential but lacks a modern website and direct booking system. I help lodges increase direct bookings by 40% using custom websites, Facebook ads, and WhatsApp automation. Would you be open to a quick chat?", toneUsed: "friendly" },
  { id: 2, businessId: 2, overallScore: 68, scoreCategory: "good" as const, websiteScore: 72, mobileScore: 65, seoScore: 58, brandingScore: 75, socialScore: 70, facebookScore: 68, adScore: 55, visibilityScore: 80, whatsappScore: 60, mapsScore: 85, detectedIssues: JSON.stringify(["SEO could be improved", "Ad campaigns not optimized"]), aiSummary: "Victoria Falls Hotel has a solid digital presence with room for improvement in SEO and paid advertising.", toneUsed: "professional" },
  { id: 3, businessId: 3, overallScore: 15, scoreCategory: "poor" as const, websiteScore: 0, mobileScore: 0, seoScore: 5, brandingScore: 20, socialScore: 18, facebookScore: 22, adScore: 10, visibilityScore: 12, whatsappScore: 50, mapsScore: 25, detectedIssues: JSON.stringify(["No website", "Inactive social media", "No booking system", "Poor online visibility"]), aiSummary: "Kariba Houseboats has minimal digital presence. Only WhatsApp is active. Massive opportunity for a complete digital overhaul.", generatedPitch: "Hi there! Your houseboat adventures look incredible on Facebook. Imagine having a stunning website where tourists can browse your fleet, check availability, and book directly. I specialize in building tourism booking systems. Interested in learning more?", toneUsed: "friendly" },
];

export const mockCrmLeads = [
  { id: 1, businessId: 1, name: "Tamarind Lodges", contactName: "John Moyo", email: "john@tamarindlodges.co.zw", phone: "+263772123456", whatsapp: "+263772123456", stage: "interested" as const, source: "discovery", estimatedValue: "3500.00", tags: ["tourism", "high-value", "website"] as string[], notes: "Interested in website + WhatsApp automation. Wants to see mockup first.", aiSummary: "High buying intent. Interested in direct booking system.", buyingIntent: "high" as const, lastActivityAt: "2026-05-15T10:30:00Z" },
  { id: 2, businessId: 3, name: "Kariba Houseboats Adventures", contactName: "Sarah Ndlovu", email: "sarah@karibahouseboats.com", phone: "+263772987654", whatsapp: "+263772987654", stage: "proposal_sent" as const, source: "discovery", estimatedValue: "2800.00", tags: ["tourism", "houseboat", "booking-system"] as string[], notes: "Proposal sent for website + booking system. Waiting for response.", aiSummary: "Proposal sent 5 days ago. AI recommends follow-up.", buyingIntent: "medium" as const, lastActivityAt: "2026-05-10T14:00:00Z" },
  { id: 3, businessId: 5, name: "Gorges Lodge", contactName: "Peter Mapfumo", email: "peter@gorgeslodge.co.zw", phone: "+263772456789", whatsapp: "+263772456789", stage: "new" as const, source: "discovery", estimatedValue: "4500.00", tags: ["tourism", "boutique", "luxury"] as string[], notes: "Premium lodge. High potential for luxury website + branding.", aiSummary: "New lead. Very high opportunity for luxury services.", buyingIntent: "high" as const, lastActivityAt: "2026-05-16T08:00:00Z" },
  { id: 4, businessId: 7, name: "Amanzi Spa & Salon", contactName: "Lisa Chiweshe", email: "lisa@amanzispa.co.zw", phone: "+263242123456", whatsapp: "+263772678901", stage: "contacted" as const, source: "discovery", estimatedValue: "1800.00", tags: ["salon", "branding", "social-media"] as string[], notes: "Contacted via WhatsApp. Interested in branding package.", aiSummary: "Responded positively to initial outreach. Follow up with branding samples.", buyingIntent: "medium" as const, lastActivityAt: "2026-05-14T16:30:00Z" },
  { id: 5, businessId: 12, name: "Chobe River Lodge", contactName: "David Kgosi", email: "david@chobelodge.co.bw", phone: "+2676250336", whatsapp: "+26774123456", stage: "negotiation" as const, source: "discovery", estimatedValue: "5200.00", tags: ["tourism", "botswana", "website", "seo"] as string[], notes: "Negotiating on price. Wants website + SEO + social media management.", aiSummary: "In negotiation. Flexible on pricing. Bundle offer recommended.", buyingIntent: "high" as const, lastActivityAt: "2026-05-13T11:00:00Z" },
  { id: 6, businessId: 10, name: "Table Mountain Safari", contactName: "James Peterson", email: "james@tablemountainsafari.co.za", phone: "+27215551234", whatsapp: "+27829876543", stage: "proposal_sent" as const, source: "discovery", estimatedValue: "3200.00", tags: ["tourism", "safari", "south-africa"] as string[], notes: "Proposal sent for complete digital package.", aiSummary: "Stuck in proposal stage for 7 days. AI recommends follow-up email.", buyingIntent: "medium" as const, lastActivityAt: "2026-05-08T09:00:00Z" },
  { id: 7, name: "Urban Fitness Gym", contactName: "Mike Chena", email: "mike@urbanfitness.co.zw", phone: "+263772111222", whatsapp: "+263772111222", stage: "won" as const, source: "manual", estimatedValue: "2200.00", tags: ["fitness", "website", "branding"] as string[], notes: "Closed deal for website + branding. Starting next week.", aiSummary: "Won deal. Ready to start project.", buyingIntent: "high" as const, lastActivityAt: "2026-05-12T15:00:00Z" },
  { id: 8, name: "Harare Book Cafe", contactName: "Anna Mupfumi", email: "anna@hararebookcafe.co.zw", phone: "+263772333444", whatsapp: "+263772333444", stage: "lost" as const, source: "discovery", estimatedValue: "1200.00", tags: ["cafe", "social-media"] as string[], notes: "Decided to go with another agency. Price was too high.", aiSummary: "Lost to competitor. Consider re-engaging in 3 months.", buyingIntent: "low" as const, lastActivityAt: "2026-05-05T10:00:00Z" },
];

export const mockCampaigns = [
  { id: 1, name: "Kariba Lodges Outreach", channel: "whatsapp" as const, status: "completed" as const, messageTemplate: "Hi {contact_name}! I noticed {business_name} has amazing tourism potential. I help lodges increase direct bookings by 40% with custom websites and WhatsApp automation. Interested in a free consultation?", tone: "friendly", service: "website", stats: { sent: 24, delivered: 22, opened: 18, replied: 8, converted: 3 } },
  { id: 2, name: "Harare Salons Campaign", channel: "facebook" as const, status: "running" as const, messageTemplate: "Hi! I help salons like yours attract more clients through professional branding and social media management. Can I send you some examples of our work?", tone: "professional", service: "branding", stats: { sent: 15, delivered: 14, opened: 10, replied: 4, converted: 1 } },
  { id: 3, name: "Victoria Falls Hotels", channel: "email" as const, status: "scheduled" as const, messageTemplate: "Dear {contact_name}, I'm reaching out to tourism businesses in Victoria Falls about improving their direct booking rates. Our clients see an average 35% increase in direct bookings. Would you be interested in a complimentary digital audit?", tone: "professional", service: "seo", scheduleAt: "2026-05-20T08:00:00Z" },
  { id: 4, name: "Safari Operators Follow-up", channel: "whatsapp" as const, status: "draft" as const, messageTemplate: "Hi! Following up on my previous message about helping safari operators boost their online bookings. I have some special packages for the upcoming peak season.", tone: "friendly", service: "facebook-ads" },
];

export const mockTemplates = [
  { id: 1, name: "Tourism Website Intro", channel: "whatsapp" as const, tone: "friendly", service: "website", content: "Hi {contact_name}! I came across {business_name} and was impressed by your reviews. I help tourism businesses increase direct bookings by 40% with stunning websites. Can I share a quick mockup of what yours could look like?", variables: ["contact_name", "business_name"] as string[], usageCount: 12 },
  { id: 2, name: "Professional SEO Audit", channel: "email" as const, tone: "professional", service: "seo", content: "Dear {contact_name}, I specialize in helping businesses like {business_name} improve their Google rankings and online visibility. I'd like to offer you a complimentary SEO audit. Would you be interested?", variables: ["contact_name", "business_name"] as string[], usageCount: 8 },
  { id: 3, name: "Luxury Branding Pitch", channel: "facebook" as const, tone: "luxury", service: "branding", content: "Good day {contact_name}. {business_name} deserves a brand identity that matches its exceptional quality. Our luxury branding packages have helped boutique properties command premium rates. Shall we discuss?", variables: ["contact_name", "business_name"] as string[], usageCount: 5 },
  { id: 4, name: "WhatsApp Automation Offer", channel: "whatsapp" as const, tone: "friendly", service: "whatsapp-automation", content: "Hi! Did you know 89% of tourists prefer booking via WhatsApp? I can set up an automated booking system for {business_name} that works 24/7. Interested in learning more?", variables: ["business_name"] as string[], usageCount: 3 },
];

export const mockActivities = [
  { id: 1, type: "discovery", description: "AI discovered Tamarind Lodges in Kariba — Very High opportunity detected", createdAt: "2026-05-16T10:30:00Z" },
  { id: 2, type: "analysis", description: "AI analysis complete for Kariba Houseboats — Overall score: 15/100 (Poor)", createdAt: "2026-05-16T09:15:00Z" },
  { id: 3, type: "outreach", description: "WhatsApp campaign 'Kariba Lodges Outreach' completed — 3 conversions", createdAt: "2026-05-15T16:00:00Z" },
  { id: 4, type: "crm_update", description: "Tamarind Lodges moved from 'Contacted' to 'Interested'", createdAt: "2026-05-15T14:30:00Z" },
  { id: 5, type: "discovery", description: "AI discovered 5 new salons in Harare with weak digital presence", createdAt: "2026-05-15T11:00:00Z" },
  { id: 6, type: "campaign", description: "Harare Salons Campaign launched — 15 recipients", createdAt: "2026-05-14T09:00:00Z" },
  { id: 7, type: "analysis", description: "AI analysis complete for Victoria Falls Hotel — Overall score: 68/100 (Good)", createdAt: "2026-05-14T08:30:00Z" },
  { id: 8, type: "agent", description: "AI Agent auto-discovered 3 high-opportunity leads in Victoria Falls", createdAt: "2026-05-13T17:00:00Z" },
];

export const mockAgentInsights = [
  { id: 1, type: "recommendation", title: "Focus on Victoria Falls tourism", description: "78% of lodges in your region have no booking system — High opportunity for direct booking websites.", action: "Find Lodges Without Direct Booking", priority: "high" },
  { id: 2, type: "alert", title: "3 leads need follow-up", description: "Chobe River Lodge, Kariba Houseboats, and Table Mountain Safari haven't been contacted in 5+ days.", action: "Send follow-ups", priority: "high" },
  { id: 3, type: "trend", title: "Tourism bookings increasing", description: "AI detected a 23% increase in tourism business searches this month.", action: "Run discovery", priority: "medium" },
  { id: 4, type: "recommendation", title: "Safari operators need SEO", description: "85% of safari operators rank below page 3 on Google for 'safari [location]' keywords.", action: "Analyze safari operators", priority: "medium" },
  { id: 5, type: "alert", title: "CRM pipeline bottleneck", description: "8 leads are stuck in 'Proposal Sent' stage for 7+ days. AI follow-up recommended.", action: "Run AI follow-up", priority: "high" },
];
